// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"
)

const countExercisesByLevelID = `-- name: CountExercisesByLevelID :one
SELECT count(*) FROM exercises WHERE level_id = $1
`

// Counts the number of exercises in a given level.
func (q *Queries) CountExercisesByLevelID(ctx context.Context, levelID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countExercisesByLevelID, levelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (level_id, exercise_type, difficulty, category, explanation, data_json, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, level_id, exercise_type, difficulty, category, explanation, data_json, sort_order, created_at
`

type CreateExerciseParams struct {
	LevelID      int32  `json:"level_id"`
	ExerciseType string `json:"exercise_type"`
	Difficulty   int32  `json:"difficulty"`
	Category     int32  `json:"category"`
	Explanation  string `json:"explanation"`
	DataJson     []byte `json:"data_json"`
	SortOrder    int32  `json:"sort_order"`
}

// Creates a new exercise and returns it.
func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRow(ctx, createExercise,
		arg.LevelID,
		arg.ExerciseType,
		arg.Difficulty,
		arg.Category,
		arg.Explanation,
		arg.DataJson,
		arg.SortOrder,
	)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.LevelID,
		&i.ExerciseType,
		&i.Difficulty,
		&i.Category,
		&i.Explanation,
		&i.DataJson,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getExercise = `-- name: GetExercise :one
SELECT id, level_id, exercise_type, difficulty, category, explanation, data_json, sort_order, created_at
FROM exercises
WHERE id = $1
`

// Gets a single exercise by its ID.
func (q *Queries) GetExercise(ctx context.Context, id int32) (Exercise, error) {
	row := q.db.QueryRow(ctx, getExercise, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.LevelID,
		&i.ExerciseType,
		&i.Difficulty,
		&i.Category,
		&i.Explanation,
		&i.DataJson,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listExercisesByLevelID = `-- name: ListExercisesByLevelID :many
SELECT id, level_id, exercise_type, difficulty, category, explanation, data_json, sort_order, created_at
FROM exercises
WHERE level_id = $1
ORDER BY sort_order
`

// Lists all exercises for a given level, ordered by sort_order.
func (q *Queries) ListExercisesByLevelID(ctx context.Context, levelID int32) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, listExercisesByLevelID, levelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Exercise{}
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.LevelID,
			&i.ExerciseType,
			&i.Difficulty,
			&i.Category,
			&i.Explanation,
			&i.DataJson,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
