// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: levels.sql

package db

import (
	"context"
)

const createLevel = `-- name: CreateLevel :one
INSERT INTO levels (level_number, theme)
VALUES ($1, $2)
RETURNING id, level_number, theme, created_at
`

type CreateLevelParams struct {
	LevelNumber int32  `json:"level_number"`
	Theme       string `json:"theme"`
}

// Creates a new level and returns it.
func (q *Queries) CreateLevel(ctx context.Context, arg CreateLevelParams) (Level, error) {
	row := q.db.QueryRow(ctx, createLevel, arg.LevelNumber, arg.Theme)
	var i Level
	err := row.Scan(
		&i.ID,
		&i.LevelNumber,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const getLevel = `-- name: GetLevel :one
SELECT id, level_number, theme, created_at
FROM levels
WHERE level_number = $1
`

// Gets a single level by its level number.
func (q *Queries) GetLevel(ctx context.Context, levelNumber int32) (Level, error) {
	row := q.db.QueryRow(ctx, getLevel, levelNumber)
	var i Level
	err := row.Scan(
		&i.ID,
		&i.LevelNumber,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const getLevelByID = `-- name: GetLevelByID :one
SELECT id, level_number, theme, created_at
FROM levels
WHERE id = $1
`

// Gets a single level by its database ID.
func (q *Queries) GetLevelByID(ctx context.Context, id int32) (Level, error) {
	row := q.db.QueryRow(ctx, getLevelByID, id)
	var i Level
	err := row.Scan(
		&i.ID,
		&i.LevelNumber,
		&i.Theme,
		&i.CreatedAt,
	)
	return i, err
}

const listLevels = `-- name: ListLevels :many
SELECT id, level_number, theme, created_at
FROM levels
ORDER BY level_number
`

// Lists all levels ordered by level number.
func (q *Queries) ListLevels(ctx context.Context) ([]Level, error) {
	rows, err := q.db.Query(ctx, listLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Level{}
	for rows.Next() {
		var i Level
		if err := rows.Scan(
			&i.ID,
			&i.LevelNumber,
			&i.Theme,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
