// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID           int32              `json:"id"`
	LevelID      int32              `json:"level_id"`
	ExerciseType string             `json:"exercise_type"`
	Difficulty   int32              `json:"difficulty"`
	Category     int32              `json:"category"`
	Explanation  string             `json:"explanation"`
	DataJson     []byte             `json:"data_json"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Level struct {
	ID          int32              `json:"id"`
	LevelNumber int32              `json:"level_number"`
	Theme       string             `json:"theme"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserProgress struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	LevelID         int32              `json:"level_id"`
	Stars           int32              `json:"stars"`
	BestTimeSeconds pgtype.Float8      `json:"best_time_seconds"`
	Unlocked        bool               `json:"unlocked"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
