// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProgress = `-- name: GetUserProgress :many
SELECT id, user_id, level_id, stars, best_time_seconds, unlocked, completed_at, created_at, updated_at
FROM user_progress
WHERE user_id = $1
ORDER BY level_id
`

// Gets all level progress for a user.
func (q *Queries) GetUserProgress(ctx context.Context, userID pgtype.UUID) ([]UserProgress, error) {
	rows, err := q.db.Query(ctx, getUserProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserProgress{}
	for rows.Next() {
		var i UserProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LevelID,
			&i.Stars,
			&i.BestTimeSeconds,
			&i.Unlocked,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProgressForLevel = `-- name: GetUserProgressForLevel :one
SELECT id, user_id, level_id, stars, best_time_seconds, unlocked, completed_at, created_at, updated_at
FROM user_progress
WHERE user_id = $1 AND level_id = $2
`

type GetUserProgressForLevelParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	LevelID int32       `json:"level_id"`
}

// Gets progress for a specific user and level.
func (q *Queries) GetUserProgressForLevel(ctx context.Context, arg GetUserProgressForLevelParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, getUserProgressForLevel, arg.UserID, arg.LevelID)
	var i UserProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LevelID,
		&i.Stars,
		&i.BestTimeSeconds,
		&i.Unlocked,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT
    COALESCE(SUM(stars), 0)::int AS total_stars,
    COUNT(CASE WHEN completed_at IS NOT NULL THEN 1 END)::int AS levels_completed,
    COUNT(*)::int AS levels_started
FROM user_progress
WHERE user_id = $1
`

type GetUserStatsRow struct {
	TotalStars      int32 `json:"total_stars"`
	LevelsCompleted int32 `json:"levels_completed"`
	LevelsStarted   int32 `json:"levels_started"`
}

// Gets aggregate stats for a user.
func (q *Queries) GetUserStats(ctx context.Context, userID pgtype.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(&i.TotalStars, &i.LevelsCompleted, &i.LevelsStarted)
	return i, err
}

const upsertUserProgress = `-- name: UpsertUserProgress :one
INSERT INTO user_progress (user_id, level_id, stars, best_time_seconds, unlocked, completed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, level_id)
DO UPDATE SET
    stars = GREATEST(user_progress.stars, EXCLUDED.stars),
    best_time_seconds = CASE
        WHEN user_progress.best_time_seconds IS NULL THEN EXCLUDED.best_time_seconds
        WHEN EXCLUDED.best_time_seconds IS NULL THEN user_progress.best_time_seconds
        ELSE LEAST(user_progress.best_time_seconds, EXCLUDED.best_time_seconds)
    END,
    unlocked = EXCLUDED.unlocked OR user_progress.unlocked,
    completed_at = COALESCE(user_progress.completed_at, EXCLUDED.completed_at),
    updated_at = now()
RETURNING id, user_id, level_id, stars, best_time_seconds, unlocked, completed_at, created_at, updated_at
`

type UpsertUserProgressParams struct {
	UserID          pgtype.UUID        `json:"user_id"`
	LevelID         int32              `json:"level_id"`
	Stars           int32              `json:"stars"`
	BestTimeSeconds pgtype.Float8      `json:"best_time_seconds"`
	Unlocked        bool               `json:"unlocked"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

// Creates or updates progress for a user on a specific level.
func (q *Queries) UpsertUserProgress(ctx context.Context, arg UpsertUserProgressParams) (UserProgress, error) {
	row := q.db.QueryRow(ctx, upsertUserProgress,
		arg.UserID,
		arg.LevelID,
		arg.Stars,
		arg.BestTimeSeconds,
		arg.Unlocked,
		arg.CompletedAt,
	)
	var i UserProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LevelID,
		&i.Stars,
		&i.BestTimeSeconds,
		&i.Unlocked,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
